spring.application.name=backend_ams
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:mysql://localhost:3306/amsdbrestDecembre2024?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=

#En cas d'utilisation app docker avec une base locale utiliser cette configuration

spring.datasource.url=jdbc:mysql://host.docker.internal:3306/amsdbrestDecembre2024?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
#Environnement Docker
#spring.datasource.url=jdbc:mysql://localhost:3306/dbams2026?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=sip2026
server.port=8081


# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

